move なんでぇな。.wav AMITARO_KANSAI_001.wav
move なんでやねん、全然ちゃうやんか、いっしょくたにせんといて。.wav AMITARO_KANSAI_002.wav
move もうほんま自分なんなん？.wav AMITARO_KANSAI_003.wav
move せやろか？.wav AMITARO_KANSAI_004.wav
move せやで。.wav AMITARO_KANSAI_005.wav
move しらんがな。.wav AMITARO_KANSAI_006.wav
move しらんけど。.wav AMITARO_KANSAI_007.wav
move しらんで。.wav AMITARO_KANSAI_008.wav
move しらんでほんまに。.wav AMITARO_KANSAI_009.wav
move しらんわ。.wav AMITARO_KANSAI_010.wav
move しらんやん。.wav AMITARO_KANSAI_011.wav
move しらんっちゅうてんねん。.wav AMITARO_KANSAI_012.wav
move しらんもんはしらん。.wav AMITARO_KANSAI_013.wav
move 自分しっとったんちゃうん？.wav AMITARO_KANSAI_014.wav
move かまへんがな。.wav AMITARO_KANSAI_015.wav
move かまへんで。.wav AMITARO_KANSAI_016.wav
move 今ええわ。.wav AMITARO_KANSAI_017.wav
move そのへん置いといて。.wav AMITARO_KANSAI_018.wav
move いらん言うてるやろ。.wav AMITARO_KANSAI_019.wav
move ほんまぁ。.wav AMITARO_KANSAI_020.wav
move さよか。.wav AMITARO_KANSAI_021.wav
move そうなんや。.wav AMITARO_KANSAI_022.wav
move そうかいな。.wav AMITARO_KANSAI_023.wav
move 好きにしはったらよろしがな。.wav AMITARO_KANSAI_024.wav
move そういうことははよ言うてぇや。.wav AMITARO_KANSAI_025.wav
move あほか、はよ謝ってきぃ！.wav AMITARO_KANSAI_026.wav
move はよしぃ。.wav AMITARO_KANSAI_027.wav
move やかましわ。.wav AMITARO_KANSAI_028.wav
move やかましい！.wav AMITARO_KANSAI_029.wav
move そんなん三個も四個も買えへんで！.wav AMITARO_KANSAI_030.wav
move 買いません！.wav AMITARO_KANSAI_031.wav
move こないだも言うたやろが。.wav AMITARO_KANSAI_032.wav
move いつも言うてるやろ。.wav AMITARO_KANSAI_033.wav
move はよ食べな先生来はるで。.wav AMITARO_KANSAI_034.wav
move 昨日お父さん来たはったん？.wav AMITARO_KANSAI_035.wav
move そうゆうたら外でなんやしたはったなぁ。.wav AMITARO_KANSAI_036.wav
move あんまちゃんと見てへんかったわ。.wav AMITARO_KANSAI_037.wav
move いやほんならゆうといたったらよかったなぁ、気ぃつかんかったわ。.wav AMITARO_KANSAI_038.wav
move ごめんごめん。.wav AMITARO_KANSAI_039.wav
move ほっぺたにえらいでっかいおできぎょうさんこさえてどないしたん、せっかくのべっぴんさんが台なしやんか。.wav AMITARO_KANSAI_040.wav
move いつまでやってんねん。.wav AMITARO_KANSAI_041.wav
move 何回ゆわすねん。.wav AMITARO_KANSAI_042.wav
move ほんまたいがいにしぃや。.wav AMITARO_KANSAI_043.wav
move 次もうゆえへんで。.wav AMITARO_KANSAI_044.wav
move ええからはよして。.wav AMITARO_KANSAI_045.wav
move うそやん。.wav AMITARO_KANSAI_046.wav
move いやほんまぁ、よかったやんおめでとう、がんばってやったもんなぁ。.wav AMITARO_KANSAI_047.wav
move ゆうてへんがなそんなこと。.wav AMITARO_KANSAI_048.wav
move ようゆうわ。.wav AMITARO_KANSAI_049.wav
move はずかしやん、やめてぇや。.wav AMITARO_KANSAI_050.wav
move またうまいことゆうて。.wav AMITARO_KANSAI_051.wav
move 行けたら行くわ。.wav AMITARO_KANSAI_052.wav
move なんでやねんな。.wav AMITARO_KANSAI_053.wav
move あかんで。.wav AMITARO_KANSAI_054.wav
move せぇへんで。.wav AMITARO_KANSAI_055.wav
move そんなんようせんわ。.wav AMITARO_KANSAI_056.wav
move できひんて。.wav AMITARO_KANSAI_057.wav
move なんてゆうたはった？.wav AMITARO_KANSAI_058.wav
move おっちゃんいてはった？.wav AMITARO_KANSAI_059.wav
move しゃあないなぁ、まけといたるわ、今日だけやで。.wav AMITARO_KANSAI_060.wav
move ええかげんなやっちゃなぁ。.wav AMITARO_KANSAI_061.wav
move そんなええかげんなことばっかりしてたらほんまそのうちえらい目あうで。.wav AMITARO_KANSAI_062.wav
move 何回もゆわさんといて。.wav AMITARO_KANSAI_063.wav
move せやからゆうたやん。.wav AMITARO_KANSAI_064.wav
move ほんまにええん？.wav AMITARO_KANSAI_065.wav
move めっちゃ助かるわぁ、ありがとう。.wav AMITARO_KANSAI_066.wav
move まいどおおきに。.wav AMITARO_KANSAI_067.wav
move 安うしとくからなんかこうてって。.wav AMITARO_KANSAI_068.wav
move あかんわこれ。.wav AMITARO_KANSAI_069.wav
move えらこっちゃ、忘れとった。.wav AMITARO_KANSAI_070.wav
move ようゆわんわ。.wav AMITARO_KANSAI_071.wav
move お嬢ちゃん何歳？かいらしねぇ。.wav AMITARO_KANSAI_072.wav
move お母さんどこいったん？.wav AMITARO_KANSAI_073.wav
move ほんまかいな、ほんならおばちゃんと一緒に待ってよか。.wav AMITARO_KANSAI_074.wav
move あめちゃんあんで、食べるか？.wav AMITARO_KANSAI_075.wav
move ちょお、やめてぇや。.wav AMITARO_KANSAI_076.wav
move あかんあかん。.wav AMITARO_KANSAI_077.wav
move ほんまかいな。.wav AMITARO_KANSAI_078.wav
move ほんまほんま。.wav AMITARO_KANSAI_079.wav
move ほんまにええんか？.wav AMITARO_KANSAI_080.wav
move せや、あんたあれどこやったん。.wav AMITARO_KANSAI_081.wav
move もうてへんわ。.wav AMITARO_KANSAI_082.wav
move なんや今日もうしんどいわ、やめやめ。.wav AMITARO_KANSAI_083.wav
move アホなことばっかりゆうて相手してられんわ。.wav AMITARO_KANSAI_084.wav
move お前なぁ…。.wav AMITARO_KANSAI_085.wav
move あとでこれほっといて。.wav AMITARO_KANSAI_086.wav
move 大事なもんやったらしっかりしもとき。.wav AMITARO_KANSAI_087.wav
move ほんまにちゃんとしもたんか？.wav AMITARO_KANSAI_088.wav
move またそこらへんほったらかしにしてたんちゃうん。.wav AMITARO_KANSAI_089.wav
move いっこも見てへんで。.wav AMITARO_KANSAI_090.wav
move こんなとこおいとったらなくすで。.wav AMITARO_KANSAI_091.wav
move いっこもうてもええー？.wav AMITARO_KANSAI_092.wav
move いらんねやったらみんな食べてまうで。.wav AMITARO_KANSAI_093.wav
move なぁて、さっきの電話なんてゆうたはったん？.wav AMITARO_KANSAI_094.wav
move なんやようわからん。.wav AMITARO_KANSAI_095.wav
move しらん、どうせまたセールスちゃうか。.wav AMITARO_KANSAI_096.wav
move なんや。.wav AMITARO_KANSAI_097.wav
move 忙し時に何回もかけてくんなっちゅうねん。.wav AMITARO_KANSAI_098.wav
move おかんどこ行ったん？.wav AMITARO_KANSAI_099.wav
move しらん、かいもんちゃうか。.wav AMITARO_KANSAI_100.wav
move おとんおらんの？.wav AMITARO_KANSAI_101.wav
move なんやお客さん来てて遅なるらしいで。.wav AMITARO_KANSAI_102.wav
move 晩ごはん何？.wav AMITARO_KANSAI_103.wav
move またたこ焼きかいな、ばあちゃんそればっかりやん、ほんま好っきゃなぁ。.wav AMITARO_KANSAI_104.wav
move じいちゃんちょっとこれゆうたって。.wav AMITARO_KANSAI_105.wav
move そんなん急に言われてもわし大阪弁しかしゃべれんし。.wav AMITARO_KANSAI_106.wav
move ねえちゃん大阪帰ってくんのん？.wav AMITARO_KANSAI_107.wav
move にいちゃんの大阪土産やて。.wav AMITARO_KANSAI_108.wav
move 関西ゆうても広いからなぁ。.wav AMITARO_KANSAI_109.wav
move でかけんねやったら帰りにマクドこうてきて。.wav AMITARO_KANSAI_110.wav
move 店どこも閉まっとったからミスドだけこうてきたわ。.wav AMITARO_KANSAI_111.wav
move そないゆうたら先週あんたになんや来とったで。.wav AMITARO_KANSAI_112.wav
move あんた寝てる間スマホずっとピコピコしとったで。.wav AMITARO_KANSAI_113.wav
move わざとちゃうわ、忘れてたんや。.wav AMITARO_KANSAI_114.wav
move いややったら自分でしぃ。.wav AMITARO_KANSAI_115.wav
move ひさしぶりやん、角まで一緒に帰ろか。.wav AMITARO_KANSAI_116.wav
move なあなあ、数学のテストどないやった？.wav AMITARO_KANSAI_117.wav
move うちは体育の後やったからめっちゃ眠たかったわ、五時間目はあかんねん。.wav AMITARO_KANSAI_118.wav
move たしかにごはんの後はあかんわ、なんか時間割がいけずやったな。.wav AMITARO_KANSAI_119.wav
move そうゆうたら聞いた？.wav AMITARO_KANSAI_120.wav
move 田中ちゃん、お子さんできたから結婚しはんねんて。.wav AMITARO_KANSAI_121.wav
move えっ、音楽の先生ほんまにやめはるん？.wav AMITARO_KANSAI_122.wav
move ほんなら次どないしはるんやろ。.wav AMITARO_KANSAI_123.wav
move 次の先生めっちゃイケメンやったらええのになぁ。.wav AMITARO_KANSAI_124.wav
move ほんまやな、イケメンええな。.wav AMITARO_KANSAI_125.wav
move なぁ、試験終わったらどないする？.wav AMITARO_KANSAI_126.wav
move どないって何が？.wav AMITARO_KANSAI_127.wav
move うちらごっつがんばったやん？.wav AMITARO_KANSAI_128.wav
move ひらパーか海遊館行こか思てたけど、もっとええとこないかな思て。.wav AMITARO_KANSAI_129.wav
move そやな、ディズニーランドとかどやろ、めっちゃバイトせんなんけど。.wav AMITARO_KANSAI_130.wav
move それええな、めっちゃ卒業旅行って感じするわ、でもゆうほどお金ないねよな。.wav AMITARO_KANSAI_131.wav
move わたしも受験終わったらバイトしぃたいけどおかん絶対勉強勉強ってまたうるさいわ。.wav AMITARO_KANSAI_132.wav
move おなかすいたわ、とりあえずファミレス行こか。.wav AMITARO_KANSAI_133.wav
move せやな、何はさておきまずは腹ごしらえや。.wav AMITARO_KANSAI_134.wav
move 新しいパフェ出てたやんな、あかんわ、また肥えてまいそうやわ。.wav AMITARO_KANSAI_135.wav
move 気にしたあかん、ダイエットは明日からっておかんもいっつもゆうてる。.wav AMITARO_KANSAI_136.wav
move なにそれどこでこうたん、めっちゃかわいいやん！.wav AMITARO_KANSAI_137.wav
move なんぼしたん？.wav AMITARO_KANSAI_138.wav
move うそやん手作りでこんなん作れんの、自分天才ちゃうん。.wav AMITARO_KANSAI_139.wav
move すごいなめっちゃええやん、こんな細かいのんようやるわ。.wav AMITARO_KANSAI_140.wav
move みっちゃんよう似合てるわ、京都の舞妓はんみたいや。.wav AMITARO_KANSAI_141.wav
move 上手やな、そんなおだててもなんも出ぇへんで。.wav AMITARO_KANSAI_142.wav
move おかえり、どやった？.wav AMITARO_KANSAI_143.wav
move あかんわめっちゃ緊張してもおた。.wav AMITARO_KANSAI_144.wav
move まさかあかんかったん？.wav AMITARO_KANSAI_145.wav
move そうゆうわけやないけど、めっちゃ困った顔したはったし、絶対変なやつや思われたわ。.wav AMITARO_KANSAI_146.wav
move そんなことないて、先輩めっちゃうれしそうにしたはったやん。.wav AMITARO_KANSAI_147.wav
move 恥ずすぎて明日から顔合わされへんわ。.wav AMITARO_KANSAI_148.wav
move 大丈夫やって、気にしすぎや、もっと自信持ち。.wav AMITARO_KANSAI_149.wav
move 自信はないけど、今日は着いて来てくれてありがとうな。.wav AMITARO_KANSAI_150.wav
move ええよこのぐらい、なんぼでもゆうて。.wav AMITARO_KANSAI_151.wav
move 水くさいな、うちらの仲やんか。.wav AMITARO_KANSAI_152.wav
move あ、先生らこれからどっか行かはるんですか？.wav AMITARO_KANSAI_153.wav
move ちゃいますよ、なんもしてませんよ。.wav AMITARO_KANSAI_154.wav
move 妹の誕生日やし今日ははよ帰ろかな思て。.wav AMITARO_KANSAI_155.wav
move また今度誘てな。.wav AMITARO_KANSAI_156.wav
move せや、あんた昨日のオリンピック見た？.wav AMITARO_KANSAI_157.wav
move あれめっちゃかっこよなかった？.wav AMITARO_KANSAI_158.wav
move ほんまあれどないなってんねやろな。.wav AMITARO_KANSAI_159.wav
move うちお父さんが持ってんで、貸したろか？.wav AMITARO_KANSAI_160.wav
move 誰もつこてへんし別にええで。.wav AMITARO_KANSAI_161.wav
move そんなん大事に大事にしもといてもしゃあないやん。.wav AMITARO_KANSAI_162.wav
move のしつけて返しますがな。.wav AMITARO_KANSAI_163.wav
move ほんなら帰りにもらいにいくわ。.wav AMITARO_KANSAI_164.wav
move ついでにちょっとおじいちゃんに会うてったって。.wav AMITARO_KANSAI_165.wav
move えらいお疲れやね、ゆっくりしていき。.wav AMITARO_KANSAI_166.wav
move ほんまごめんな。.wav AMITARO_KANSAI_167.wav
move うわ、ほんまに全部一人で食べたん？.wav AMITARO_KANSAI_168.wav
move ごめん、つい食べてもうた。.wav AMITARO_KANSAI_169.wav
move ちっこいおなかやのにようそんな入んなぁ。.wav AMITARO_KANSAI_170.wav
move せやせや、ようゆうてくれたわ。.wav AMITARO_KANSAI_171.wav
move なんやこれむずすぎるやろ。.wav AMITARO_KANSAI_172.wav
move ようそんなん知ってんな、さすがええとこのぼんぼんや。.wav AMITARO_KANSAI_173.wav
move あほなこといいなや。.wav AMITARO_KANSAI_174.wav
move できるわけあるかいなそんなもん。.wav AMITARO_KANSAI_175.wav
move 別になんもむずない、やれる時にやったらええだけや。.wav AMITARO_KANSAI_176.wav
move ごちゃごちゃゆうてんとなんしか手ぇ動かし。.wav AMITARO_KANSAI_177.wav
move なんぼ泣いてもやらなおわれへんで。.wav AMITARO_KANSAI_178.wav
move これももうどけてまおか、ぎっちぎちに干したあるけど乾いてんかこれ。.wav AMITARO_KANSAI_179.wav
move 知らんけどめんどくさいし全部入れといたらええやろ。.wav AMITARO_KANSAI_180.wav
move ほんまええかげんなやっちゃな。.wav AMITARO_KANSAI_181.wav
move なんかあったらごめんなさいゆうたらええねん。.wav AMITARO_KANSAI_182.wav
move そんなんおかんやったるやん、貸してみ。.wav AMITARO_KANSAI_183.wav
move ええわ、いらんて。.wav AMITARO_KANSAI_184.wav
move なんでぇな、ちょっと見してみぃて。.wav AMITARO_KANSAI_185.wav
move あいつほんまいらんことしぃやな。.wav AMITARO_KANSAI_186.wav
move 儲かりまっか？.wav AMITARO_KANSAI_187.wav
move ぼちぼちでんな。.wav AMITARO_KANSAI_188.wav
move なんやそれ、あほらし。.wav AMITARO_KANSAI_189.wav
move このピッツァマルゲリータが目に入らんか。.wav AMITARO_KANSAI_190.wav
move なんでそないなんねん。.wav AMITARO_KANSAI_191.wav
move そんなええもんちゃうわ、なんかもうちょっとそれっぽいやつないん？.wav AMITARO_KANSAI_192.wav
move 最後の方絶対ちゃうやろが。.wav AMITARO_KANSAI_193.wav
move バレてもた？.wav AMITARO_KANSAI_194.wav
move ほんまにそんなやったらあかんよ、わかってる？.wav AMITARO_KANSAI_195.wav
move 自分でちゃんとせなあかんで。.wav AMITARO_KANSAI_196.wav
move あそこの店そんなん売ってんねや、めずらしね。.wav AMITARO_KANSAI_197.wav
move そらせやろ、そんなもん比べたらあかんやろ。.wav AMITARO_KANSAI_198.wav
move やったんはやったけどもっかいせんなんわ。.wav AMITARO_KANSAI_199.wav
move まいど、また来てな。.wav AMITARO_KANSAI_200.wav
move あんたほんま目ぇ悪なんで。.wav AMITARO_KANSAI_201.wav
move 覚えてへんの？.wav AMITARO_KANSAI_202.wav
move 手ぇあろといで。.wav AMITARO_KANSAI_203.wav
move なんやここ、お好み焼きあれへんがな。.wav AMITARO_KANSAI_204.wav
move おばあちゃん、かしわの唐揚げあんで。.wav AMITARO_KANSAI_205.wav
move ほんまいらんことしいのあかんたれやな、この子は。.wav AMITARO_KANSAI_206.wav
move 今日ははよ寝んなんからはよ食べてまい。.wav AMITARO_KANSAI_207.wav
move 焼きそばぐらいなんぼでも作ったるから喧嘩しな。.wav AMITARO_KANSAI_208.wav
move せっかくミナミ来たし通天閣んとこで串カツ食べてからえべっさん行こか。.wav AMITARO_KANSAI_209.wav
move どこで拾てきたんよそんなもん。.wav AMITARO_KANSAI_210.wav
move もうええわ。.wav AMITARO_KANSAI_211.wav
move しつこいで。.wav AMITARO_KANSAI_212.wav
move なんべんも言わさんといてゆうてるやろ。.wav AMITARO_KANSAI_213.wav
move ちゃんと前見て歩き。.wav AMITARO_KANSAI_214.wav
move 出しっぱなしにしといたらあかんで。.wav AMITARO_KANSAI_215.wav
move いちいち数えんでええねん、もうほっといてんか。.wav AMITARO_KANSAI_216.wav
move 好きにしなはれ。.wav AMITARO_KANSAI_217.wav
move 買うたらええがな。.wav AMITARO_KANSAI_218.wav
move おかあちゃんとおとうちゃんに聞いとくわ。.wav AMITARO_KANSAI_219.wav
move スーパーに駄菓子屋のおばちゃんいたはったわ。.wav AMITARO_KANSAI_220.wav
move あんたちっちゃい時あそこのお兄ちゃんらによう遊んでもうてんで、覚えてる？.wav AMITARO_KANSAI_221.wav
move ちょっと見いひん間にえらい重たなったなぁ、もう何年生？.wav AMITARO_KANSAI_222.wav
move ほんまか、大きなったなあ、学校行ったら勉強がんばりや。.wav AMITARO_KANSAI_223.wav
move みんなで大事に使い、弟と妹にもいっぱいさしたってな。.wav AMITARO_KANSAI_224.wav
move いっぺん試しに使てみたらは？.wav AMITARO_KANSAI_225.wav
move 家でよう相談して、ほんでから決めたらええやん。.wav AMITARO_KANSAI_226.wav
move 誰にも内緒やで。.wav AMITARO_KANSAI_227.wav
move ごはん多めに炊いといたけどあの子らぎょうさん食べるし足りひんのちゃう、みたらし団子も買うとこか。.wav AMITARO_KANSAI_228.wav
move もうええっちゅうねん、おかんあいつらになんぼほど食べさす気やねん。.wav AMITARO_KANSAI_229.wav
move せやけど取り合いなったらかわいそやんか。.wav AMITARO_KANSAI_230.wav
move なるかあほ、そんだけ食べさしたら相撲取りなるわ。.wav AMITARO_KANSAI_231.wav
move なれへんよそんなん、あの子らどんだけ食べてもガリガリやんかうらやましい。.wav AMITARO_KANSAI_232.wav
move そんなんゆうんやったらおかんも運動したらええねん。.wav AMITARO_KANSAI_233.wav
move あかんわおかん最近腰痛いねん、もう年やわ、年寄りやわ。.wav AMITARO_KANSAI_234.wav
move どうせ後でおなかすいたゆうねんからしっかり食べとき。.wav AMITARO_KANSAI_235.wav
move わしよりようしゃべる癖にどこがやねん。.wav AMITARO_KANSAI_236.wav
move せやなぁ、ぼちぼちやらんなんなぁ。.wav AMITARO_KANSAI_237.wav
move じいちゃんに似てきたなぁ、すっかりいっちょまえやねぇ。.wav AMITARO_KANSAI_238.wav
move ほんまにみんな持ってんねんて、なぁ買うてぇやぁ。.wav AMITARO_KANSAI_239.wav
move そんなお金はどこにもおまへん、だいたいみんなて誰や。.wav AMITARO_KANSAI_240.wav
move そんなんゆうたかてあれへんもんはあれへん、自分でどないかしぃ。.wav AMITARO_KANSAI_241.wav
move よそはよそ、うちはうちや。.wav AMITARO_KANSAI_242.wav
move やったらできるやんか、めっちゃきれなったやん。.wav AMITARO_KANSAI_243.wav
move おうたらちゃんとお礼ゆうといてよ！.wav AMITARO_KANSAI_244.wav
move えらいおもろそうなことしてるやん、なんで声かけてくれへんかったんよ、わたしも呼んでぇや。.wav AMITARO_KANSAI_245.wav
move 五十日やしえらい混んどったんちゃうん？.wav AMITARO_KANSAI_246.wav
move なんぼもせんうちにゆうてくんなや、せわしないやっちゃなぁ。.wav AMITARO_KANSAI_247.wav
move 薬ばっかりこんな持たされたら重うてかなわんわ、おなかタプタプなんで。.wav AMITARO_KANSAI_248.wav
move 先生ついでに男前にしといてんか。.wav AMITARO_KANSAI_249.wav
move お父さんまた調子ええことばっかりゆうて、もう相手せんといてください。.wav AMITARO_KANSAI_250.wav
move 元が元やねんからそない変わるかいな、むちゃくちゃゆうわ。.wav AMITARO_KANSAI_251.wav
move なんも痛ない、そんなんでいちいち泣けへんよ。.wav AMITARO_KANSAI_252.wav
move なんぼほど待たすねん、日ぃ暮れてまうわ。.wav AMITARO_KANSAI_253.wav
move いやもへったくれもあれへん！.wav AMITARO_KANSAI_254.wav
move えらい待たしてもうてすんまへんなぁ。.wav AMITARO_KANSAI_255.wav
move 重た、こんなん腰いわすわ。.wav AMITARO_KANSAI_256.wav
move 家で娘さん待ったはんのん？.wav AMITARO_KANSAI_257.wav
move ほんなはよせなあかんねぇ。.wav AMITARO_KANSAI_258.wav
move 息子さんにも手伝うてもうてね、重たいから絶対一人でやったらあかんよ。.wav AMITARO_KANSAI_259.wav
move はいはい、なんべんもゆわんでもわかてんがな。.wav AMITARO_KANSAI_260.wav
move あかんわもういっこも歩かれへん、くたびれたわ、おなかぺこぺこや。.wav AMITARO_KANSAI_261.wav
move おかんしんどいから自分でごはんよそといて。.wav AMITARO_KANSAI_262.wav
move そんなん一個ずつちんたら運んでられへんやろ、ばあちゃん持ったるからみんなここ入れてまい。.wav AMITARO_KANSAI_263.wav
move こんなちっさいもんがなんでそんなすんねんな、ぼったくりやんか。.wav AMITARO_KANSAI_264.wav
move いっつもあんたとこでぎょうさん買うたってるやんか、なんぼかまけてぇな。.wav AMITARO_KANSAI_265.wav
move そうかあいつにゆうてもそないなるんか、えらこっちゃやなぁ、ほなどうしょうかな。.wav AMITARO_KANSAI_266.wav
move あんな、前から思ててんけど、大判焼きって御座候に似てへん？.wav AMITARO_KANSAI_267.wav
move またいつものとっからようわからん電話やわ、しつこいなぁ。.wav AMITARO_KANSAI_268.wav
move どんだけかけてもおらんもんわおらんっちゅうねん。.wav AMITARO_KANSAI_269.wav
move もうないわ、こんでもう終わりや終わり。.wav AMITARO_KANSAI_270.wav
move ほなまたね、気ぃつけて帰りや。.wav AMITARO_KANSAI_271.wav
move よかったねぇ、おめでとうさん。.wav AMITARO_KANSAI_272.wav
move いやほんまにええん？.wav AMITARO_KANSAI_273.wav
move ほなもうとくで？.wav AMITARO_KANSAI_274.wav
move あかんかったらまたゆうてよ？.wav AMITARO_KANSAI_275.wav
move どないしょうかな、いっぺんやってはみるけど、あかんかったらごめんな？.wav AMITARO_KANSAI_276.wav
move 蕎麦屋の出前やないけど、そんなんゆうてる間に来るんちゃうか。.wav AMITARO_KANSAI_277.wav
move 聞いたで、えらい大変やってんて？.wav AMITARO_KANSAI_278.wav
move ほんまなぁ、せやけどなんものうてよかったやん。.wav AMITARO_KANSAI_279.wav
move これで向こう怪我でもしてたらえらいこっちゃで、なぁ？.wav AMITARO_KANSAI_280.wav
move なんぼも使てへんのになんで動けへんねんこれ、おかしいやん、バッタモンちゃうか。.wav AMITARO_KANSAI_281.wav
move まぁしゃあないわ、あほなことゆうてんとやってまお。.wav AMITARO_KANSAI_282.wav
move おっちゃんもわざとやないねんからしゃあないがな。.wav AMITARO_KANSAI_283.wav
move そうゆうたらあの話ってほんまですのん？.wav AMITARO_KANSAI_284.wav
move いいやわぁ、なんでぇな、全然ちゃうよ。.wav AMITARO_KANSAI_285.wav
move ほんまやっとこさやで。.wav AMITARO_KANSAI_286.wav
move あんたなぁ、遅なるんやったら遅なるで電話ぐらいしぃ。.wav AMITARO_KANSAI_287.wav
move いっこも帰ってけぇへんしどないなってるんか思て心配したやんか。.wav AMITARO_KANSAI_288.wav
move おばちゃんもゆうたってください、ほんまいっこもゆうこと聞けへん。.wav AMITARO_KANSAI_289.wav
move ほんで結局どないしたんよ、ちゃんとあったん？.wav AMITARO_KANSAI_290.wav
move そうかもう七五三か、お嬢ちゃんも綺麗なおべべ着せてもうて、みんなおそろいでよろしですなぁ。.wav AMITARO_KANSAI_291.wav
move 堪忍堪忍、すっかり忘れとったわ、お宮さん今日やったなぁ。.wav AMITARO_KANSAI_292.wav
move 時間ないさかい服もうこれでええやろ、とりあえず行こか。.wav AMITARO_KANSAI_293.wav
move あんたなんか忘れてへんか？.wav AMITARO_KANSAI_294.wav
move 鍵や鍵、なんでおこづかいやねん。.wav AMITARO_KANSAI_295.wav
move 今ちょっと忙しねん、後にしてんか。.wav AMITARO_KANSAI_296.wav
move もうおばあちゃんそんなんええて、いらんて。.wav AMITARO_KANSAI_297.wav
move ぎょうさん家にあるからそんなん。.wav AMITARO_KANSAI_298.wav
move もうほんま気ぃ使わんでええて、気持ちだけもうとくから。.wav AMITARO_KANSAI_299.wav
move ほんなまた今度なんかしたって、もうそれでええから。.wav AMITARO_KANSAI_300.wav
move もういっつもありがとう、ごめんな。.wav AMITARO_KANSAI_301.wav
move ほなまた来るわな、おやすみ。.wav AMITARO_KANSAI_302.wav
move やっぱり田中さんいたはれへんかった？.wav AMITARO_KANSAI_303.wav
move あそこの家いっつもせやねん、またどっかで会うた時にでもゆうとくわ。.wav AMITARO_KANSAI_304.wav
move なんでやねんな、人をバケモンみたいに。.wav AMITARO_KANSAI_305.wav
move そんなんゆうてへんやん。.wav AMITARO_KANSAI_306.wav
move あんたほんまええかげんにしぃや、そのうちバチ当たんで。.wav AMITARO_KANSAI_307.wav
move どっちゃなってもほんねんからどっちゃでもええがな。.wav AMITARO_KANSAI_308.wav
move 友達に聞いといで。.wav AMITARO_KANSAI_309.wav
move ええてええて、おっちゃんがやっといたるから任しとき、出世払いや。.wav AMITARO_KANSAI_310.wav
move ぼちぼち行かんなんなぁ。.wav AMITARO_KANSAI_311.wav
move せやせや、冷蔵庫に菜っ葉の炊いたんもあんで。.wav AMITARO_KANSAI_312.wav
move あんたそれ破いたらあかんで。.wav AMITARO_KANSAI_313.wav
move あんたもうほんまええかげんにしぃや！.wav AMITARO_KANSAI_314.wav
move たいがいにせえよ。.wav AMITARO_KANSAI_315.wav
move どっか行くんやったら行きしなにこれポスト入れといて。.wav AMITARO_KANSAI_316.wav
move えらいええもん用意してもうて、ほんならせっかくやから呼ばれるわ。.wav AMITARO_KANSAI_317.wav
move 先呼ばれさしてもうたよ。.wav AMITARO_KANSAI_318.wav
move おおきに、ごちそうさん。.wav AMITARO_KANSAI_319.wav
move おつけもんもあんで、食べたらわ？.wav AMITARO_KANSAI_320.wav
move えらいようけあんなあ、えげつな。.wav AMITARO_KANSAI_321.wav
move なんやなんや、なんやえらいけったいなかっこしてんなぁ。.wav AMITARO_KANSAI_322.wav
move あかんあかん、そんな上も下も一緒くたにせんといて！.wav AMITARO_KANSAI_323.wav
move うわほんま自分最悪やな、ようそんなえげつないことするわ。.wav AMITARO_KANSAI_324.wav
move あんたらこんなとこに居ったらあかんで。.wav KANSAI_001.wav
move せやけどそんなこと言うたらなんもできへんで？.wav KANSAI_002.wav
move せやな、それでいこか。.wav KANSAI_003.wav
move あんた暇かえ？.wav KANSAI_004.wav
move 今からやったら惣菜も安なるさかい、ぼちぼち買いにいこか。.wav KANSAI_005.wav
move あーせやせや、思い出したわそれやわ。.wav KANSAI_006.wav
move なんか忘れとるんよなぁ、なんやったかいなぁ。.wav KANSAI_007.wav
move しもた、ゴミ出すの忘れとったわ。.wav KANSAI_008.wav
move まぁしゃあないな。.wav KANSAI_009.wav
move なんともけったいな天気やな。.wav KANSAI_010.wav
move こらもうあかんわ、こんなんよぉしやんわ。.wav KANSAI_011.wav
move こないだあそこの店入ったんやけどな、めっちゃうまかってん。.wav KANSAI_012.wav
move モタモタせんとはよ行きぃ。.wav KANSAI_013.wav
move ドアホ、ほんなことよぉしよかれ。.wav KANSAI_014.wav
move ええやん、めっちゃええやん。.wav KANSAI_015.wav
move 今日はあんま持っとらへんねん、これでかにしてくれんやろか。.wav KANSAI_016.wav
move アイツ自分から言うた癖にけぇへんやんけ。.wav KANSAI_017.wav
move まだこやんのかいな。.wav KANSAI_018.wav
move どないしよかなぁ、明日でもええんやけどなぁ。.wav KANSAI_019.wav
move 我がのことはするさかいに、ほっといてくれんかい。.wav KANSAI_020.wav
move あっかんわ、やってもうた。.wav KANSAI_021.wav
move しもたわ、これあかん。.wav KANSAI_022.wav
move あいた、アホなことした。.wav KANSAI_023.wav
move あいつまだ帰ってこぉへんのかいな、どこほっつき歩いとんねん。.wav KANSAI_024.wav
move あんたこれなんぼやろか。.wav KANSAI_025.wav
move あんた刺身あめてまうで、はよ食ぅたりぃ。.wav KANSAI_026.wav
move 前のこと思たらだいぶよぉなったと思うけどな。.wav KANSAI_027.wav
move 何すんねんアホ、ボケぇ。.wav KANSAI_028.wav
move もぉーどないしたらええと思う？.wav KANSAI_029.wav
move すまなんだな、これで堪忍な。.wav KANSAI_030.wav
move まめぐるんやのうて、もうちょいこう、綺麗に食わんかい。.wav KANSAI_031.wav
move 何言うとるかよおわからんけど、まぁいっぺん見してみぃ。.wav KANSAI_032.wav
move 貸してみぃ、やったるさかい。.wav KANSAI_033.wav
move もぉだいぶつこてしもたで、こんだけしかあらへん。.wav KANSAI_034.wav
move やけどなぁ、そうなってしもたらどないもこないもならへんで。.wav KANSAI_035.wav
move そうは言うてもやな、あんたが言うみたいにうまいこといかへんねん。.wav KANSAI_036.wav
move なんや、またしもたったんか。.wav KANSAI_037.wav
move 車を動かしはったんはあんたやろ？.wav KANSAI_038.wav
move あんたよぉしやんやろ？.wav KANSAI_039.wav
move 予定はささってですに？.wav KANSAI_040.wav
move なんべんもおんなじ事しよるに？.wav KANSAI_041.wav
move よおさんはっとると思ったんに、えらいはっとるのすけないやんけ。.wav KANSAI_042.wav
move せやでか、せやでこんなチビっとしかはっとらんのか。.wav KANSAI_043.wav
move 水でうめたったらええんとちゃうの。.wav KANSAI_044.wav
move 貼ったばっかやで、いごかしたらんようにな。.wav KANSAI_045.wav
move あかんっちゅうたやんけえ。.wav KANSAI_046.wav
move わりゃいてこましたろか。.wav KANSAI_047.wav
move さらのやつやのに、触んりょったらわやにしてもうた。.wav KANSAI_048.wav
move そんなむちゃくちゃいろたったらあかんわい。.wav KANSAI_049.wav
move そこのどんつきにあるカゴへなおしたってくれんかい？.wav KANSAI_050.wav
move やめたれさ、あんまりしたらまくれてくで。.wav KANSAI_051.wav
move どもならんで、まぁこれでよしにしよか。.wav KANSAI_052.wav
move 言うたら言うた時間に来やんかいあほんだらあ。.wav KANSAI_053.wav
move またどやされんでえ。.wav KANSAI_054.wav
move 昨日テレビ見いよったけど、あんまおもんなかったで。.wav KANSAI_055.wav
move おもっしょないやつらぁ見やへんよ。.wav KANSAI_056.wav
move またなんかよおさん持ってきはったでぇ？.wav KANSAI_057.wav
move 使わんのやったらなおしときい。.wav KANSAI_058.wav
move あんた刺身あめてまうで食うてまいい。.wav KANSAI_059.wav
move あそこは車つむでなぁ。.wav KANSAI_060.wav
move ちゅうちゅうたこかいな、あい、ちょっきし。.wav KANSAI_061.wav
move 水道凍ってもうた、水でやへん。.wav KANSAI_062.wav
move なんべんやってもでえへんのやわ。.wav KANSAI_063.wav
move 邪魔や邪魔、のかんかい。.wav KANSAI_064.wav
move なおさへんのやったらほったるでえ。.wav KANSAI_065.wav
move きんのうテレビ見ぃよったらさ、どえらい事故のニュースしとったで。.wav KANSAI_066.wav
move いっぺんに食うたらえづくで。.wav KANSAI_067.wav
move あいつそんなこと言わなんだと思うけどなぁ。.wav KANSAI_068.wav
move さかむけのかさぶたはいろたらあかんで、なおらんで。.wav KANSAI_069.wav
move まぁかいごおあくんにゃあ。.wav KANSAI_070.wav
move ほな、あんじょうよろしゅうな。.wav KANSAI_071.wav
move この道ズーッと行って左へクッっと曲がったらすぐよ。.wav KANSAI_072.wav
move なんかさっきビューッて行ってもうたで。.wav KANSAI_073.wav
move あんただいぶシュッとしたな。.wav KANSAI_074.wav
move これシュッってしたらシャンとなるでさ。.wav KANSAI_075.wav
move あいつにだっきゃ言われとうないがな。.wav KANSAI_076.wav
move みてみぃ、池に鯉が泳んぎょるよ。.wav KANSAI_077.wav
move なにぃ、そないぎょおさんもろてきたん。.wav KANSAI_078.wav
move どないやろなぁ、今日日そんな店もあらへんでなぁ。.wav KANSAI_079.wav
move ほいだら、またよろしゅうたのんます。.wav KANSAI_080.wav
move いつものあれ買うてこよかと思ったんやけどなぁ、なかってん。.wav KANSAI_081.wav
move なんでそんなずぼらなことしはるん？.wav KANSAI_082.wav
move あいつほんまどもならんやっちゃな。.wav KANSAI_083.wav
move そんな燃えるようなもんストーブのねきらぁにおいたらあかんやんか。.wav KANSAI_084.wav
move 朝の国道は空いとるでスーッて行けるでさ。.wav KANSAI_085.wav
move ほやさかい、あんたなっとらんって言われるんさぁ。.wav KANSAI_086.wav
move あんたも大概ねちこいやっちゃなぁ。.wav KANSAI_087.wav
move そんなほたえるからやに。.wav KANSAI_088.wav
move もうギチギチいっぱいまで入っとるで。.wav KANSAI_089.wav
move 答え合わせしとらんで、合うとるかどうかわからへん。.wav KANSAI_090.wav
move 牛乳飲んどるときにわらかしてくんな。.wav KANSAI_091.wav
move なんでぇ、宿題でとらへんで単位出さへんよ。.wav KANSAI_092.wav
move ドラマいっつも見とるけど、先週分だけ見逃してもた。.wav KANSAI_093.wav
move 毎度のことでタバコ咥えて原チャ乗っててん、あほやあいつ。.wav KANSAI_094.wav
move あの人そんなことしてはるの？.wav KANSAI_095.wav
move さっき言うとらん言うたやないか、なんや違うんかい。.wav KANSAI_096.wav
move 弁当ガーッと掻き込んで、チャッチャと仕事に戻らんかい。.wav KANSAI_097.wav
move なんでそないモタモタしたはるのん？.wav KANSAI_098.wav
move あんたがシャンとしとれば、こんなんせんでもよかったんやけどなぁ。.wav KANSAI_099.wav
move あんな遠いとこ行っきょるん？.wav KANSAI_100.wav
move こやへんとは言わへんけどな？.wav KANSAI_101.wav
move 病み上がりやでな、気張るけども、べべたでも堪忍してくれい？.wav KANSAI_102.wav
move 折角誘いに来ったのになんや、あいつおらんのか。.wav KANSAI_103.wav
move 部品出やんでよおしやんとか言うてきたもんで、もぉごおわいてきてどやしたったわ。.wav KANSAI_104.wav
move これ使こてまうけど、ええかい？.wav KANSAI_105.wav
move あかんやん無いなるやん。.wav KANSAI_106.wav
move 買うてくれるんやったらええけど。.wav KANSAI_107.wav
move えらいよおけ入れたな、溶けやんととごっとるで。.wav KANSAI_108.wav
move そんなことばっかしぃよったら、またふてたるで？.wav KANSAI_109.wav
move まぁかい、ごおわいてきてな。.wav KANSAI_110.wav
move うちきたらゲームさしたるよ。.wav KANSAI_111.wav
move 時間なってもバスけえへんやんけ。.wav KANSAI_112.wav
move ちゃあうちゃあう、そんなことしやへんよ。.wav KANSAI_113.wav
move のかしてくれるのはええけど、ほかさんといてな。.wav KANSAI_114.wav
move あいつちゃらんぽらんやで、誰かおらんと機械しもたるで。.wav KANSAI_115.wav
move 端っからできやんようにしとってん。.wav KANSAI_116.wav
move うちはかまんよ、好きにさしたれさ。.wav KANSAI_117.wav
move あんたそんな重たいもんやめときぃ、腰しまうで。.wav KANSAI_118.wav