move 女の子がキッキッ嬉しそうや。.wav ITA_KANSAI_RECITATION_001.wav
move ツァツォに旅行した。.wav ITA_KANSAI_RECITATION_002.wav
move 民衆がテュルリー宮殿に侵入した。.wav ITA_KANSAI_RECITATION_003.wav
move ハイチ共和国でトゥーサンルーヴェルテュールが勝利を収められたんは、実際黄熱病のおかげやった。.wav ITA_KANSAI_RECITATION_004.wav
move レジャンドルは民衆をテュルリー宮殿に招ぇた。.wav ITA_KANSAI_RECITATION_005.wav
move 助言はできへんとデュパンは言うた。.wav ITA_KANSAI_RECITATION_006.wav
move フランス人シェフと日本人シェフは全然ちゃう。.wav ITA_KANSAI_RECITATION_007.wav
move 中国の外交団にアタッシェとして派遣された。.wav ITA_KANSAI_RECITATION_008.wav
move ファシズム勢力との総力戦に臨む。.wav ITA_KANSAI_RECITATION_009.wav
move 家具商人のフィシェルは、荷車と仔馬を貸してくれた。.wav ITA_KANSAI_RECITATION_010.wav
move ローカル路線にはファンも多い。.wav ITA_KANSAI_RECITATION_011.wav
move フェイントで相手をかわしてからシュートでフィニッシュした。.wav ITA_KANSAI_RECITATION_012.wav
move 1877、プフェファーにより浸透現象が発見された。.wav ITA_KANSAI_RECITATION_013.wav
move 揺れるフェリーに乗るんは私にとって苦行や。.wav ITA_KANSAI_RECITATION_014.wav
move ホルロ・アラ・ティタルッフォっちゅう特別な料理も出たんや。.wav ITA_KANSAI_RECITATION_015.wav
move 笛の音がなったらウサギのキッドが早速ぴょんと跳ねた。.wav ITA_KANSAI_RECITATION_016.wav
move あの旅客は噂のキャフェに行くようや。.wav ITA_KANSAI_RECITATION_017.wav
move 目標は一等賞や。.wav ITA_KANSAI_RECITATION_018.wav
move ウサギのキッドは気分よぉピョン、またピョンと飛び続けた。.wav ITA_KANSAI_RECITATION_019.wav
move アフタヌーンティーを楽しもか。.wav ITA_KANSAI_RECITATION_020.wav
move 彼女はティピカルなフェミニストや。.wav ITA_KANSAI_RECITATION_021.wav
move 助手らぁとミッツィは探しとる書類を見つけられなんだ。.wav ITA_KANSAI_RECITATION_022.wav
move フィレンツェ、パドヴァ、ヴェネツィアはどれもイタリアの都市や。.wav ITA_KANSAI_RECITATION_023.wav
move 楽譜へ次のように書いてあるんが、エーフェリチェです。.wav ITA_KANSAI_RECITATION_024.wav
move ショペンハウエルとニーチェの哲学書を本棚から取り出した。.wav ITA_KANSAI_RECITATION_025.wav
move 早いとこ召使い全員に知らせたろ。.wav ITA_KANSAI_RECITATION_026.wav
move 重たい綿入を脱いで、あわせへ着替える。.wav ITA_KANSAI_RECITATION_027.wav
move ボストンで、とあるチョプスイ屋へ入って夕飯を食ぅた。.wav ITA_KANSAI_RECITATION_028.wav
move ろくすっぽ休憩をとらんと働いた。.wav ITA_KANSAI_RECITATION_029.wav
move かつて一人で国府へ侵入した。.wav ITA_KANSAI_RECITATION_030.wav
move せやけど、今日お前がここへ御入来になったんは、どないなご用なん？.wav ITA_KANSAI_RECITATION_031.wav
move サブフランチャイザーを増やして目指せ百店舗。.wav ITA_KANSAI_RECITATION_032.wav
move 四国でお遍路を行脚しょう。.wav ITA_KANSAI_RECITATION_033.wav
move いつもの通りギャンギャン泣き出しよった。.wav ITA_KANSAI_RECITATION_034.wav
move 先生は、立ったままニュースを見とりました。.wav ITA_KANSAI_RECITATION_035.wav
move 私はギョッと目ぇを見開いた。.wav ITA_KANSAI_RECITATION_036.wav
move せや、最近きやへん友達へニューイヤーカードを送ったろ。.wav ITA_KANSAI_RECITATION_037.wav
move 家政婦は休みに洒落たアウターウェアに身を包み一人で屋台を楽しんだ。.wav ITA_KANSAI_RECITATION_038.wav
move ウォッカのお供には塩漬けのきゅうりがあうで。.wav ITA_KANSAI_RECITATION_039.wav
move 山の向こうのミュンヒェンの人らぁが攻撃をしかけた。.wav ITA_KANSAI_RECITATION_040.wav
move ボスニア国境からの攻撃により、十一月にヴァリェヴォが占領された。.wav ITA_KANSAI_RECITATION_041.wav
move シルヴィウスはデュボアと呼ばれとったフランスのユグノーの家に生まれた。.wav ITA_KANSAI_RECITATION_042.wav
move そのほかにあたしに出来ることはなかったんです、百合枝は涙声んなった。.wav ITA_KANSAI_RECITATION_043.wav
move ガル博士百体近く。.wav ITA_KANSAI_RECITATION_044.wav
move 日本政府からの百兆円を超える予算要求。.wav ITA_KANSAI_RECITATION_045.wav
move 写経の美しさに私は仰天してしもおた。.wav ITA_KANSAI_RECITATION_046.wav
move ソプラノ歌手ポリランダチョは歌劇アイーダの特別名歌手と評判や。.wav ITA_KANSAI_RECITATION_047.wav
move あんた最初百ポンド渡したやろ、足りやんのか、がめついなぁあんたもぉ。.wav ITA_KANSAI_RECITATION_048.wav
move 社長がしたってくれ言うたはったでなぁ。.wav ITA_KANSAI_RECITATION_049.wav
move どうも気まぐれっちゅうもんは多少メフィスティックなもんであるらしい。.wav ITA_KANSAI_RECITATION_050.wav
move 蛙がピョコピョコ飛び回っとります。.wav ITA_KANSAI_RECITATION_051.wav
move 魔境に足を踏み入れる。.wav ITA_KANSAI_RECITATION_052.wav
move ヴァンダーヴォットタイム中は、いわゆるパーティーのようで晴れやかや。.wav ITA_KANSAI_RECITATION_053.wav
move スピリッツっちゅうんは蒸留酒の事です。.wav ITA_KANSAI_RECITATION_054.wav
move ヌルシアのベネディクトゥスはアポロン神殿を壊し、ベネディクト会の修道院を建てた。.wav ITA_KANSAI_RECITATION_055.wav
move ちょうどそんとき、デストゥパーゴがコップをもって立ちあがりました。.wav ITA_KANSAI_RECITATION_056.wav
move パフィーのグッズが残らんと部屋に落ち着いた。.wav ITA_KANSAI_RECITATION_057.wav
move エピファーノフは財布どっかやったった。.wav ITA_KANSAI_RECITATION_058.wav
move ポピュラーなソフトを使てセキュアな状態を復旧する。.wav ITA_KANSAI_RECITATION_059.wav
move チョコの在庫あったやろか？.wav ITA_KANSAI_RECITATION_060.wav
move おめえ、これ仕込んだるのに、どんだけ時間かかるか知っとるか。.wav ITA_KANSAI_RECITATION_061.wav
move それに、このほうが体のためにゃずっとええんやからね。.wav ITA_KANSAI_RECITATION_062.wav
move 夏休みに、トラアヴェミュンへ旅行した。.wav ITA_KANSAI_RECITATION_063.wav
move ここで一緒にウェイクフィールドの叔母を待った。.wav ITA_KANSAI_RECITATION_064.wav
move 八つになるウォルターと一緒に出た兄弟がおったが、ウォルターだけ発見された。.wav ITA_KANSAI_RECITATION_065.wav
move 最初のジョブはウォーリアがええと思います。.wav ITA_KANSAI_RECITATION_066.wav
move およそ六百メートル先を右折です。.wav ITA_KANSAI_RECITATION_067.wav
move 新店オープンのレセプションに沢山のお客さんを招待した。.wav ITA_KANSAI_RECITATION_068.wav
move 脚本作者ピエール・オービュルナンの給仕クレマンが、主人の書斎の戸ぉを大切そうに開いた。.wav ITA_KANSAI_RECITATION_069.wav
move われわれは、天主教徒か長老教会派のもので、天主教徒が多数を占めとる。.wav ITA_KANSAI_RECITATION_070.wav
move 結局のところお互い五十歩百歩や。.wav ITA_KANSAI_RECITATION_071.wav
move 突拍子もない話やけど、決して嘘やない。.wav ITA_KANSAI_RECITATION_072.wav
move ネットで懸案の解決を目指す。.wav ITA_KANSAI_RECITATION_073.wav
move 切れ味鋭いペティナイフは使い勝手がええ。.wav ITA_KANSAI_RECITATION_074.wav
move 指をくわえてぴゅーと一声口笛を吹いた。.wav ITA_KANSAI_RECITATION_075.wav
move クレンペ教頭は無骨な男やが、自分の学問の秘密には深く浸っとった。.wav ITA_KANSAI_RECITATION_076.wav
move 尻尾ふりたて、ひげくいそらす。.wav ITA_KANSAI_RECITATION_077.wav
move すべての獲物を望みどおりに狙う技術がある。.wav ITA_KANSAI_RECITATION_078.wav
move グニャグニャが無理やからタコいらうの嫌いやねん。.wav ITA_KANSAI_RECITATION_079.wav
move 私らは、抽象的意識的自己を否定することで、ほんまの自己とは身心一如やということを知る。.wav ITA_KANSAI_RECITATION_080.wav
move 鹿島明神が釘で刺し貫いて、魚が動かんようにしとる。.wav ITA_KANSAI_RECITATION_081.wav
move 私は手始めに、同業者から話を聞く努力をした。.wav ITA_KANSAI_RECITATION_082.wav
move がいなうれしそうにしてぴょんぴょん跳ねて出てったで。.wav ITA_KANSAI_RECITATION_083.wav
move 二分だけのオルガン演奏で終わってしもた。.wav ITA_KANSAI_RECITATION_084.wav
move おもろいけど、ニセ教会に騙されたらあかんやろ。.wav ITA_KANSAI_RECITATION_085.wav
move およそ百年前には、薬剤として薬屋で売っとった。.wav ITA_KANSAI_RECITATION_086.wav
move いっそ脚本家を目指した方がええかとも考えた。.wav ITA_KANSAI_RECITATION_087.wav
move この書物に誤謬があっても、純一であらへん何ものにもインフェクトせぇへんやろ。.wav ITA_KANSAI_RECITATION_088.wav
move 仏教はインド由来の宗教や。.wav ITA_KANSAI_RECITATION_089.wav
move キャリーバッグは旅行に必須。.wav ITA_KANSAI_RECITATION_090.wav
move 本番前はメチャメチャ不安になる。.wav ITA_KANSAI_RECITATION_091.wav
move 三角関数においてピュタゴラスの定理は必須や。.wav ITA_KANSAI_RECITATION_092.wav
move 著名なラニョン博士が患者と接しとった。.wav ITA_KANSAI_RECITATION_093.wav
move おもちゃの刀を持った少年が、お百度石に寄りかかっとる。.wav ITA_KANSAI_RECITATION_094.wav
move 食料の補給が急務やと伝えられた。.wav ITA_KANSAI_RECITATION_095.wav
move 展示会であの作品のみ不評やった。.wav ITA_KANSAI_RECITATION_096.wav
move 客人をもてなすのは当然や。.wav ITA_KANSAI_RECITATION_097.wav
move 旅行客が楽しめるように工夫したろ。.wav ITA_KANSAI_RECITATION_098.wav
move こんなアホみたいなニュースあろかれ。.wav ITA_KANSAI_RECITATION_099.wav
move ちっさい星をぎょうさん描いた、水飲みグラスはよぉある。.wav ITA_KANSAI_RECITATION_100.wav
move 柄は、猫の尻尾みたいに、尖端をぶるぶると震わせながら、動いてく。.wav ITA_KANSAI_RECITATION_101.wav
move 店始めた時はなぁ、プリンがいっちゃん売れとってん。.wav ITA_KANSAI_RECITATION_102.wav
move ロナルドホープ大尉が大将のマンションへ急行したんや。.wav ITA_KANSAI_RECITATION_103.wav
move 日刊センティナル紙のヘプバンや。.wav ITA_KANSAI_RECITATION_104.wav
move この宝石は、一個百万円以上のお値段です。.wav ITA_KANSAI_RECITATION_105.wav
move チョウチョと仲良くなるんやから。.wav ITA_KANSAI_RECITATION_106.wav
move 宇宙では、エントロピーは無際限に増大しとる。.wav ITA_KANSAI_RECITATION_107.wav
move 川の中流に集落がある。.wav ITA_KANSAI_RECITATION_108.wav
move 頼むで話さして貰えんやろか。.wav ITA_KANSAI_RECITATION_109.wav
move お隣さんが蒟蒻を持ってきはる。.wav ITA_KANSAI_RECITATION_110.wav
move パーティーは楽しむもんです。.wav ITA_KANSAI_RECITATION_111.wav
move おてつってでっかぁ書かれた番茶茶碗は、これらの人々の前に置かれた。.wav ITA_KANSAI_RECITATION_112.wav
move 私のポケットの中には携帯電話が入っとります。.wav ITA_KANSAI_RECITATION_113.wav
move 彼は今度は牧場へ行って、沼地で小悪魔の尻尾一つ見つけました。.wav ITA_KANSAI_RECITATION_114.wav
move 五行説による占いがあるっちゅう情報あり。.wav ITA_KANSAI_RECITATION_115.wav
move テンプル君、既に真逆やってゆうた。.wav ITA_KANSAI_RECITATION_116.wav
move 世界中の様々なモニュメントを訪ね歩いた。.wav ITA_KANSAI_RECITATION_117.wav
move アンソニー・ホプキンスは有名な俳優や。.wav ITA_KANSAI_RECITATION_118.wav
move 彼女は出来るだけぴったりと耳をあてて聴きました。.wav ITA_KANSAI_RECITATION_119.wav
move 茶一つ参らんか、まあええで。.wav ITA_KANSAI_RECITATION_120.wav
move ほんまボヤだけですんでよかったなぁ。.wav ITA_KANSAI_RECITATION_121.wav
move モンタギュ・ゴーシ卿がマンチェスターに来はった。.wav ITA_KANSAI_RECITATION_122.wav
move ウィスキーの水割りをガッツリ飲んだ。.wav ITA_KANSAI_RECITATION_123.wav
move これぁお祭りを若いもんに見せるにゃ持ってこいっちゅうやつや。.wav ITA_KANSAI_RECITATION_124.wav
move 私はイメージカラーをピンクに決めた。.wav ITA_KANSAI_RECITATION_125.wav
move ムニャムニャ、もう食われへん。.wav ITA_KANSAI_RECITATION_126.wav
move 満洲は雨季以外には雨はそんな降らへんって言うとるけど、あしが満洲におるとっきゃ、大戦中やったからかもしれんけど、えらい雨あ多かった。.wav ITA_KANSAI_RECITATION_127.wav
move 均一居酒屋やったら一番よぉ売れても二人で八千円くらいやろな。.wav ITA_KANSAI_RECITATION_128.wav
move 願いをかなえたる。.wav ITA_KANSAI_RECITATION_129.wav
move 最初しんどかったけど、花も園芸も好きやったし、失意が癒やされんこともないなぁ。.wav ITA_KANSAI_RECITATION_130.wav
move ペピス爺さんはまぁ寝るらしいで。.wav ITA_KANSAI_RECITATION_131.wav
move はよウィルキンソンを呼びに行かんかい。.wav ITA_KANSAI_RECITATION_132.wav
move お昼前ジャスパーさんとこへ再びお邪魔しました。.wav ITA_KANSAI_RECITATION_133.wav
move その竜の百の頭が恐ろしい。.wav ITA_KANSAI_RECITATION_134.wav
move 必要なミョウバンの量はプリントに書いてあるさかい。.wav ITA_KANSAI_RECITATION_135.wav
move マリー・ロジェはパヴェサンタンの家を出た。.wav ITA_KANSAI_RECITATION_136.wav
move 読み進むにつれ、ますます興味が湧いた。.wav ITA_KANSAI_RECITATION_137.wav
move 笑いかけもって一二歩近寄った。.wav ITA_KANSAI_RECITATION_138.wav
move 地表を緑化して、温暖化を抑止する能力を強ぉする。.wav ITA_KANSAI_RECITATION_139.wav
move ハサミでプツッと切った切れ端をペットにやった.wav ITA_KANSAI_RECITATION_140.wav
move ホームランを打つ。.wav ITA_KANSAI_RECITATION_141.wav
move プレゼントをギャロウェイさんに渡したってくれ。.wav ITA_KANSAI_RECITATION_142.wav
move ケプラーの法則について直接私に聞いてきよった。.wav ITA_KANSAI_RECITATION_143.wav
move ウェンディーズはハンバーガー屋さんやし。.wav ITA_KANSAI_RECITATION_144.wav
move しかし氷河はアルプスだけにあるもんやない。.wav ITA_KANSAI_RECITATION_145.wav
move この先百年も抹茶は衰退せぇへん。.wav ITA_KANSAI_RECITATION_146.wav
move 自分を評価するんは会社であって、あんまりちょけたことしとったら失脚につながるっちゅうことや。.wav ITA_KANSAI_RECITATION_147.wav
move 夜に吹く風のヒュウヒュウいう音が私を不安にさせる。.wav ITA_KANSAI_RECITATION_148.wav
move 可愛い華奢な女の子。.wav ITA_KANSAI_RECITATION_149.wav
move 水中の金魚をすくうためのポイ。.wav ITA_KANSAI_RECITATION_150.wav
move グレンエルギンはウィスキーの蒸留所や。.wav ITA_KANSAI_RECITATION_151.wav
move 一寸法師が、ヒョコヒョコと彼の方へ近づいた。.wav ITA_KANSAI_RECITATION_152.wav
move 連中はリビングでぺちゃくちゃ喋って、警戒しとらへん。.wav ITA_KANSAI_RECITATION_153.wav
move 平一郎はシャツ一枚になって絹物の布団の中へ潜りこんだ。.wav ITA_KANSAI_RECITATION_154.wav
move 下京区に引っ越す。.wav ITA_KANSAI_RECITATION_155.wav
move あいつの言うことはなんちゅうか妙な感じがあらへんか。.wav ITA_KANSAI_RECITATION_156.wav
move この事業所はなぁ、百人以上の人が勤めとってん。.wav ITA_KANSAI_RECITATION_157.wav
move わたしの家だけやなく、近所の住居といわず、商店といわず、バラックの家々はみんな草花を植えとる。.wav ITA_KANSAI_RECITATION_158.wav
move どのみちあしは馬の世話をしたらなあかんで、外行こか。.wav ITA_KANSAI_RECITATION_159.wav
move ヤン・セチャンっちゅうお笑い芸人。.wav ITA_KANSAI_RECITATION_160.wav
move 男が妙な顔をして、一瞬残忍になった。.wav ITA_KANSAI_RECITATION_161.wav
move 普及活動に幻滅した。.wav ITA_KANSAI_RECITATION_162.wav
move 雨がぽつぽつときとる。.wav ITA_KANSAI_RECITATION_163.wav
move ペリウィンクルやプランティンはブルーアイや。.wav ITA_KANSAI_RECITATION_164.wav
move 姫や侍女たちが、キンポウゲやタンポポの花を持って、彼の方へ駆け寄ってった。.wav ITA_KANSAI_RECITATION_165.wav
move 皆の協力のおかげで帰郷できた。.wav ITA_KANSAI_RECITATION_166.wav
move ウォルターとウォードが入室すると、ノラが真っ赤になった。.wav ITA_KANSAI_RECITATION_167.wav
move 今の持ち札やとあがれんと終わる。.wav ITA_KANSAI_RECITATION_168.wav
move 勉強しとるで話しかけやんといてぇ。.wav ITA_KANSAI_RECITATION_169.wav
move レパードの花壇が枯れきってもうた。.wav ITA_KANSAI_RECITATION_170.wav
move 蒸留酒にミョウバンを加える。.wav ITA_KANSAI_RECITATION_171.wav
move 取っつきにくい女中が三人おる。.wav ITA_KANSAI_RECITATION_172.wav
move レインボーブリッジは東京の名所。.wav ITA_KANSAI_RECITATION_173.wav
move 卑怯もんは悪党や。.wav ITA_KANSAI_RECITATION_174.wav
move 急に海へ飛び込んだ。.wav ITA_KANSAI_RECITATION_175.wav
move 仕事はよおけあります。.wav ITA_KANSAI_RECITATION_176.wav
move 葉巻パイプはありましたやろか。.wav ITA_KANSAI_RECITATION_177.wav
move 八百屋に行って百円で大根を買うた。.wav ITA_KANSAI_RECITATION_178.wav
move 般若っちゅうんは鬼女の能面の事や。.wav ITA_KANSAI_RECITATION_179.wav
move 日本へ行くには船か飛行機が必要や。.wav ITA_KANSAI_RECITATION_180.wav
move せやけどパーで回るんも難しい。.wav ITA_KANSAI_RECITATION_181.wav
move のぼせんよおに入浴するんはお湯の量と温度が大事。.wav ITA_KANSAI_RECITATION_182.wav
move 鬼太郎くんは冗談半分でパチりにいって怪我した。.wav ITA_KANSAI_RECITATION_183.wav
move バーニ医師がピシッと答えた。.wav ITA_KANSAI_RECITATION_184.wav
move なんかおもっしゃいことしぃよんで。.wav ITA_KANSAI_RECITATION_185.wav
move 私の病気は先天性なんや。.wav ITA_KANSAI_RECITATION_186.wav
move 三国志の関羽っちゅう将軍はめっちゃ有名や。.wav ITA_KANSAI_RECITATION_187.wav
move どえらい仕事やけど辛抱しとる。.wav ITA_KANSAI_RECITATION_188.wav
move 町の女房らしい二人連れが、日傘を持って入ってきよった。.wav ITA_KANSAI_RECITATION_189.wav
move 名をツァウォツキイというた。.wav ITA_KANSAI_RECITATION_190.wav
move 飲み会の参加を拒否した。.wav ITA_KANSAI_RECITATION_191.wav
move お母ちゃんがビックリ仰天したのも無理はあらへん。.wav ITA_KANSAI_RECITATION_192.wav
move セファドールはめまいを抑える薬や。.wav ITA_KANSAI_RECITATION_193.wav
move 明の一訓詁学者は、宋代典籍の一つにあげとる茶せんの形状を思い起こすに苦しんどる。.wav ITA_KANSAI_RECITATION_194.wav
move 深海魚は見た目はアレやけど食うてみたら旨いことが多い。.wav ITA_KANSAI_RECITATION_195.wav
move ニューヨークでイヴニングポストの記事に注目した。.wav ITA_KANSAI_RECITATION_196.wav
move 確かに牛乳とコーンフレークの相性は抜群や。.wav ITA_KANSAI_RECITATION_197.wav
move その一は、明治三十七年の九月八日か九日の夜とおぼえとる。.wav ITA_KANSAI_RECITATION_198.wav
move マルメゾンの店主はジェシーとは仲良しや。.wav ITA_KANSAI_RECITATION_199.wav
move 釣竿を肩にかけた処士あり。.wav ITA_KANSAI_RECITATION_200.wav
move 最新鋭機に乗り込んでもた。.wav ITA_KANSAI_RECITATION_201.wav
move 誰かが後ろへ来て、変な声で叫びよったのでぞっとした。.wav ITA_KANSAI_RECITATION_202.wav
move おおでらの石段の前へ立ち止まって、その出て来るんを待ちあわせた。.wav ITA_KANSAI_RECITATION_203.wav
move 未解決の懸案を持って重役と対峙する。.wav ITA_KANSAI_RECITATION_204.wav
move 薄月の光が庭を照らす。.wav ITA_KANSAI_RECITATION_205.wav
move 犯人がどっちの部屋へ入ったかわからへん。.wav ITA_KANSAI_RECITATION_206.wav
move 元々なんぼか川があってな、そん中の渓谷から出た氷河が一本に合流しててん。.wav ITA_KANSAI_RECITATION_207.wav
move ディスカッションを進める。.wav ITA_KANSAI_RECITATION_208.wav
move 九頭竜明神を祭るために灯篭をながす。.wav ITA_KANSAI_RECITATION_209.wav
move 今回の資料作りはめっちゃよぉ考えなあかんかったけど、こないだやっと終わった。.wav ITA_KANSAI_RECITATION_210.wav
move 骨子をしっかりと組み立てる。.wav ITA_KANSAI_RECITATION_211.wav
move 気球にのって空を楽しむ。.wav ITA_KANSAI_RECITATION_212.wav
move うどん屋の窯やないんやからまともなことの一つでも言うたらどうや。.wav ITA_KANSAI_RECITATION_213.wav
move あいつら幕のあいだに木戸の外散歩しとんねん。.wav ITA_KANSAI_RECITATION_214.wav
move 過去の数々の奇病が治るようになりつつある。.wav ITA_KANSAI_RECITATION_215.wav
move 買うた人はポンプを直したらなあかんって事に気ぃついた。.wav ITA_KANSAI_RECITATION_216.wav
move あの子自身は、レジ業務をしぃたいと思とるみたいやで。.wav ITA_KANSAI_RECITATION_217.wav
move 地毛は金色なんや。.wav ITA_KANSAI_RECITATION_218.wav
move 鉛筆は折れやすぅてかなんわ。.wav ITA_KANSAI_RECITATION_219.wav
move ヒポクラテスは医学の父いうて呼ばれとります。.wav ITA_KANSAI_RECITATION_220.wav
move せやけど商人は、国ざかいのすぐ近くへ住みよって、やっぱり前と同じようにやりよる。.wav ITA_KANSAI_RECITATION_221.wav
move 今まで明るかった二階の窓は、いきなりまっくらになってもうた。.wav ITA_KANSAI_RECITATION_222.wav
move アスファルトに囲まれた中にケヤキの木ぃが一本。.wav ITA_KANSAI_RECITATION_223.wav
move 名札を用意する。.wav ITA_KANSAI_RECITATION_224.wav
move マッチョな男性はモテるらしいで。.wav ITA_KANSAI_RECITATION_225.wav
move 社務所の人が言うとったんは嘘やあらへんかった。.wav ITA_KANSAI_RECITATION_226.wav
move 行楽シーズンの京都は人でごった返しとる。.wav ITA_KANSAI_RECITATION_227.wav
move どっからかパチパチと音が聞こえる。.wav ITA_KANSAI_RECITATION_228.wav
move プロ野球はどのチームが優勝するやろか？.wav ITA_KANSAI_RECITATION_229.wav
move せやけど、これやったらまるで私が誘拐しましたと自首して出るようなもんで、そんなアホなことをするやつはおらへん。.wav ITA_KANSAI_RECITATION_230.wav
move 切望しぃつつ、主を待っとる。.wav ITA_KANSAI_RECITATION_231.wav
move しばらくしたらパチパチっちゅう音もないなった。.wav ITA_KANSAI_RECITATION_232.wav
move 身分をわきまえず放った狂言。.wav ITA_KANSAI_RECITATION_233.wav
move 天を翔ける竜の姿は神秘的や。.wav ITA_KANSAI_RECITATION_234.wav
move 私の精神と一脈相通じるものがあると思た。.wav ITA_KANSAI_RECITATION_235.wav
move 皆も球場に行こ。.wav ITA_KANSAI_RECITATION_236.wav
move コペルニクスはポーランドの天文学者や。.wav ITA_KANSAI_RECITATION_237.wav
move 海沿いの旅館は眺めがええ。.wav ITA_KANSAI_RECITATION_238.wav
move 集中しとると周りが見えへんのねん。.wav ITA_KANSAI_RECITATION_239.wav
move 春木座は今日の本郷座や。.wav ITA_KANSAI_RECITATION_240.wav
move 私の手ぇを引っ張るようにして、手のひらへくれよった。.wav ITA_KANSAI_RECITATION_241.wav
move 北海の荒波は、その氷の絶壁の根を噛んで、激しく飛沫を散らしとる。.wav ITA_KANSAI_RECITATION_242.wav
move 戦意を喪失させるんが勝利への近道。.wav ITA_KANSAI_RECITATION_243.wav
move がちょうを飼う。.wav ITA_KANSAI_RECITATION_244.wav
move ふぁふぁと笑いながら楽しく手拍子。.wav ITA_KANSAI_RECITATION_245.wav
move 従軍記者は大尉相当の待遇を受ける。.wav ITA_KANSAI_RECITATION_246.wav
move 茶碗にかかってまうくらい、シャツの袖がふくらかやから、掻き抱く体に茶碗を持った。.wav ITA_KANSAI_RECITATION_247.wav
move 色々隠して今日まで犯人と一緒におる。.wav ITA_KANSAI_RECITATION_248.wav
move 浦子は寝ながら息を引いた。.wav ITA_KANSAI_RECITATION_249.wav
move 兄がはみごにされた。.wav ITA_KANSAI_RECITATION_250.wav
move 彼は不服そうに呟いた。.wav ITA_KANSAI_RECITATION_251.wav
move パチモンばっかとちごて、ほんまもんのドイツ将校やら兵卒のヘルメットを売っとるのもあるんやわ。.wav ITA_KANSAI_RECITATION_252.wav
move 彼女と一緒におるとほっこりする。.wav ITA_KANSAI_RECITATION_253.wav
move 困っとる人に向けて寄付をしたった。.wav ITA_KANSAI_RECITATION_254.wav
move 落ち込んどるんか、うつむいてじっとしとる。.wav ITA_KANSAI_RECITATION_255.wav
move 改良が進むとパンはどんどんおいしなる。.wav ITA_KANSAI_RECITATION_256.wav
move こないなことを言いもって、いらちなおじいさんは下駄を突っかけて、そそくさと出てってしもた。.wav ITA_KANSAI_RECITATION_257.wav
move 彼女と初デートの今日は夢うつつ。.wav ITA_KANSAI_RECITATION_258.wav
move おんなじ東京の名をよぶにも、今後はおそらく旧東京と新東京とに区別されるやろう。.wav ITA_KANSAI_RECITATION_259.wav
move 腰振りを二分間続ける。.wav ITA_KANSAI_RECITATION_260.wav
move 腰抜けはどっかいってもうた。.wav ITA_KANSAI_RECITATION_261.wav
move 絵葉書と一緒に銀色のルアーをマッシュに送った。.wav ITA_KANSAI_RECITATION_262.wav
move オムライスにはケチャップが一番。.wav ITA_KANSAI_RECITATION_263.wav
move ストレスは適度に発散したらなあかんよ。.wav ITA_KANSAI_RECITATION_264.wav
move これがないと始まらへんでなぁ。.wav ITA_KANSAI_RECITATION_265.wav
move 中学生ん時、避暑旅行中に体調を崩した。.wav ITA_KANSAI_RECITATION_266.wav
move 軍医は病院の門に入るのである。.wav ITA_KANSAI_RECITATION_267.wav
move 一日中明るい白夜は、一切太陽が沈まへんことで起こります。.wav ITA_KANSAI_RECITATION_268.wav
move もう、あんたにばかりも精一杯、誰にも見せられます体やないんです。.wav ITA_KANSAI_RECITATION_269.wav
move みんな揃って海に飛び込んだ。.wav ITA_KANSAI_RECITATION_270.wav
move なんやそら、話にならへんわ。.wav ITA_KANSAI_RECITATION_271.wav
move 腸チフスは怖い病気。.wav ITA_KANSAI_RECITATION_272.wav
move 排球はバレーボールの事や。.wav ITA_KANSAI_RECITATION_273.wav
move マッチを買いに入ったんかな。.wav ITA_KANSAI_RECITATION_274.wav
move 盆栽は風情がある。.wav ITA_KANSAI_RECITATION_275.wav
move やがて陪審員は合議をするために法廷を出てった。.wav ITA_KANSAI_RECITATION_276.wav
move 芸術の求める永遠性に疑問を感じる。.wav ITA_KANSAI_RECITATION_277.wav
move 聞きつけて、件の嫗、ぶるぶるとかぶりをふった。.wav ITA_KANSAI_RECITATION_278.wav
move キェルツェを通ってドビェに、ザリピェからミェイに行く。.wav ITA_KANSAI_RECITATION_279.wav
move マリアーンスケー・ラーズニェを訪れる。.wav ITA_KANSAI_RECITATION_280.wav
move 乳牛を見ながら、レテュの入ったピッツァを食べる。.wav ITA_KANSAI_RECITATION_281.wav
move ウドゥの奏者を施療した。.wav ITA_KANSAI_RECITATION_282.wav
move インスティテュートで、リデュースの話と併せて、ルデュックの話も聞いた。.wav ITA_KANSAI_RECITATION_283.wav
move ギェナーを見てイェーイと叫ぶ。.wav ITA_KANSAI_RECITATION_284.wav
move スィーディーを聞きながら、でゃーこんを食べる。.wav ITA_KANSAI_RECITATION_285.wav
move テョさんはズィーブラを見た。.wav ITA_KANSAI_RECITATION_286.wav
move レヴォリューション。レギュレーション。エデュケーション。.wav ITA_KANSAI_RECITATION_287.wav
move ブレンドデョート。ラーテャン。.wav ITA_KANSAI_RECITATION_288.wav
move あっあの。いっいえ。えっえぇ。おっおい。んーとなぁ。.wav ITA_KANSAI_RECITATION_289.wav
move いぶかしげに見上げた雨雲から、琥珀色のドラゴンがギュンと現れた。.wav ITA_KANSAI_RECITATION_290.wav
move 布でギュギュっとヌンチャクを縛る。.wav ITA_KANSAI_RECITATION_291.wav
move 服を脱ぐけど、いっつも上下がひっくり返っとる。.wav ITA_KANSAI_RECITATION_292.wav
move 放課後の音楽室で、高音を頑張って出した。.wav ITA_KANSAI_RECITATION_293.wav
move モゴモゴしながら言うてもギャグはおもんないねん。.wav ITA_KANSAI_RECITATION_294.wav
move 海水魚の漁業の一環として、稚魚が育てられとる。.wav ITA_KANSAI_RECITATION_295.wav
move ムンムンとした熱気に、あの淡水魚もへとへとになっとる。.wav ITA_KANSAI_RECITATION_296.wav
move ヘスティア所長は、十二音音楽の作法を知っとる。.wav ITA_KANSAI_RECITATION_297.wav
move 主催のやつは、このフェスはあんま人が入らへんことを、セシルから聞いた。.wav ITA_KANSAI_RECITATION_298.wav
move おかんは、サフランライスと、さつまいもの入ったシチューと、ポトフをハフハフしながら食べた。.wav ITA_KANSAI_RECITATION_299.wav
move そして、左京と千紗はヘファ駅へ着いた。.wav ITA_KANSAI_RECITATION_300.wav
move 根本と曽原は主君を批判した。.wav ITA_KANSAI_RECITATION_301.wav
move ケケっと笑いながら、津原はパトカーへ乗った。.wav ITA_KANSAI_RECITATION_302.wav
move キュキュッと鳴らした靴でパスを出した。.wav ITA_KANSAI_RECITATION_303.wav
move ティファニーはパピーにムギュッと抱き着きながら、チュチュッとキスをし、センキュと言うた。.wav ITA_KANSAI_RECITATION_304.wav
move その義軍は、一ヘクタールほふく前進をした。.wav ITA_KANSAI_RECITATION_305.wav
move へへっと、きゃつは媚びへつらった。.wav ITA_KANSAI_RECITATION_306.wav
move ほとんどの被調査者は、写真を車載した。.wav ITA_KANSAI_RECITATION_307.wav
move 補佐が、一酸化炭素中毒になるっちゅうハプニングは起きへんかった。.wav ITA_KANSAI_RECITATION_308.wav
move スチューデントが被災するファクターを、可能な限り取り払う。.wav ITA_KANSAI_RECITATION_309.wav
move カフェとは、ブレックファストとして、フォカッチャを食える場所でもある。.wav ITA_KANSAI_RECITATION_310.wav
move 普通、初級者やと、高音を伸ばすやつはできへん。.wav ITA_KANSAI_RECITATION_311.wav
move 彼からしたら、左中間から見る景色は貴重やった。.wav ITA_KANSAI_RECITATION_312.wav
move シェパードと同居しとるときに、フォスターはその格付け表を見た。.wav ITA_KANSAI_RECITATION_313.wav
move 去々年、虚数とヘ長調について学んだ。.wav ITA_KANSAI_RECITATION_314.wav
move 脚立の上でヒュヒューと風が吹くと、彼は背筋をシャンとした。.wav ITA_KANSAI_RECITATION_315.wav
move 昼にはペスカトーレを、夜には寿司をパクパク食べた。.wav ITA_KANSAI_RECITATION_316.wav
move ケフィアのことをいうとるこの本は、初版やと三百部くらいやったけど、次からだんだんと増えてった。.wav ITA_KANSAI_RECITATION_317.wav
move 皮膚が私のフェチや。.wav ITA_KANSAI_RECITATION_318.wav
move 社販で巨富を築くっちゅう、彼の目論見は途中でへし折られた。.wav ITA_KANSAI_RECITATION_319.wav
move 左表のとおりの支出になるんが、ある意味うちの社風ちゅうやつやな。.wav ITA_KANSAI_RECITATION_320.wav
move この古風な酒瓢は故郷のもんや。.wav ITA_KANSAI_RECITATION_321.wav
move そのほつれが腐敗しとるいうんは、誇張した表現やと思う。.wav ITA_KANSAI_RECITATION_322.wav
move その映画に出とる彼が、主犯である可能性はフィフティーフィフティーってやつや。.wav ITA_KANSAI_RECITATION_323.wav
move チュクンの波長は、パツンと一緒や。.wav ITA_KANSAI_RECITATION_324.wav