move えっ、うっせやん。.wav ITA_KANSAI_EMOTION_001.wav
move シュヴァイツァーの爪の垢煎じて飲ましたりたいわ。.wav ITA_KANSAI_EMOTION_002.wav
move デーヴィスさんはえらい疲れとるように見えるでぇ。.wav ITA_KANSAI_EMOTION_003.wav
move スティーヴはジェーンから手紙をもろたらしんやわ。.wav ITA_KANSAI_EMOTION_004.wav
move あの子はモーツァルトとかベートーヴェンとかの、古典派の作曲家が好っきゃねん。.wav ITA_KANSAI_EMOTION_005.wav
move ストラットフォード・オン・エイヴォンは、シェイクスピアの生まれたとこやけど、毎年多くの観光客が訪れます。.wav ITA_KANSAI_EMOTION_006.wav
move あいつピューマ慣らすのに、どえらい難儀したっちゅう話やで。.wav ITA_KANSAI_EMOTION_007.wav
move あいつがクビになるっちゅうんもけったいな話やなぁ。.wav ITA_KANSAI_EMOTION_008.wav
move クリスはヴァンパイア・ナイトを倒した。.wav ITA_KANSAI_EMOTION_009.wav
move あいつのあだ名も言い得て妙ってやつやんな。.wav ITA_KANSAI_EMOTION_010.wav
move イタリア旅行で彼は、いくつか景勝の地として有名な都市、ゆうたら、ナポリやフィレンツェを訪れた。.wav ITA_KANSAI_EMOTION_011.wav
move ゼロっちゅう概念は、ヒンドゥー文化に由来しとる。.wav ITA_KANSAI_EMOTION_012.wav
move そのいたずら娘はそっ知らん顔をした。.wav ITA_KANSAI_EMOTION_013.wav
move スミスさん、ピエール・デュボワをご紹介しますわ。私の親友やねん。.wav ITA_KANSAI_EMOTION_014.wav
move どないすんの、この店。完ッ全に閑古鳥鳴いてもおとるやんか。.wav ITA_KANSAI_EMOTION_015.wav
move 頂上へ着いたら皆でヤッホーと叫んだ。.wav ITA_KANSAI_EMOTION_016.wav
move あっベルが鳴っとる。.wav ITA_KANSAI_EMOTION_017.wav
move 彼女は彼にぴょこんとおじぎをした。.wav ITA_KANSAI_EMOTION_018.wav
move 男子生徒のめいめいが、帽子に学校のバッジをつけとります。.wav ITA_KANSAI_EMOTION_019.wav
move しもた、ヒューズ飛んでしもた。.wav ITA_KANSAI_EMOTION_020.wav
move あたしはポピュラー音楽が聞きたいねん。.wav ITA_KANSAI_EMOTION_021.wav
move 猫はにゃーにゃーと鳴く。.wav ITA_KANSAI_EMOTION_022.wav
move 私のいっちゃん上の兄が父の名代としてその集まりに出た。.wav ITA_KANSAI_EMOTION_023.wav
move 彼は首相にインタビューした。.wav ITA_KANSAI_EMOTION_024.wav
move あの会社がえらい勢いででっかなったんはあれや、なんちゅうかその、何とも言えへん戦略によるもんやったちゅうことやな。.wav ITA_KANSAI_EMOTION_025.wav
move 私はいっつもミネラルウォーターを持って歩いとる。.wav ITA_KANSAI_EMOTION_026.wav
move その子はカバン開けてうちの鍵探したんやけど、見つからへんかってん。.wav ITA_KANSAI_EMOTION_027.wav
move あの子がスタッフをまとめれると思います？.wav ITA_KANSAI_EMOTION_028.wav
move 牛乳はあんたの体にええやろ、毎日飲んだほうがええに。.wav ITA_KANSAI_EMOTION_029.wav
move あんたは流感になりかけとるか、もっとえらい病気かもしれへん。.wav ITA_KANSAI_EMOTION_030.wav
move 彼女はその事件を、生き生きとした筆致で描写した。.wav ITA_KANSAI_EMOTION_031.wav
move 彼は自らの生涯を、インドで病人をよぉしたるのに捧げるつもりや。.wav ITA_KANSAI_EMOTION_032.wav
move 奇妙なやつで、あいつは人から言われぇへんと口を聞かへん。.wav ITA_KANSAI_EMOTION_033.wav
move あしらその山脈で地元のガイドさん雇ってん。.wav ITA_KANSAI_EMOTION_034.wav
move 彼女は息子にうちで行儀よおするようにゆうた。.wav ITA_KANSAI_EMOTION_035.wav
move 彼はライフルを拾てきて、それで標的をねろた。.wav ITA_KANSAI_EMOTION_036.wav
move 私はこの本に八百円もはろたんやで？.wav ITA_KANSAI_EMOTION_037.wav
move がいな気分悪りなって入院したんやけど、いうてたいしたことなかった。.wav ITA_KANSAI_EMOTION_038.wav
move アフィ狙いの釣り記事ってやっちゃね。英語関係のコミュのあっちゃこっちゃにマルチポストしとるわ。.wav ITA_KANSAI_EMOTION_039.wav
move トラベラーズチェックを現金に替えてくれるんはこの窓口やろか？.wav ITA_KANSAI_EMOTION_040.wav
move 今日の映画は、サウンド・オブ・ミュージックやで。.wav ITA_KANSAI_EMOTION_041.wav
move 大体うちら日本人は、他所の国の言葉を話すのにちょっとビビりすぎや。.wav ITA_KANSAI_EMOTION_042.wav
move 店の人は私のこと分かってくれる様んなって、私はいっつもおんなじウェイトレスさんに応対してもろとった。.wav ITA_KANSAI_EMOTION_043.wav
move この丘からは何百万っちゅう星が見える。.wav ITA_KANSAI_EMOTION_044.wav
move あの子は大学へ行ったら、親に迷惑かからん様にしたろと思とった。.wav ITA_KANSAI_EMOTION_045.wav
move サブマリンのペリスコープが、水中からにょーんと突き出とった。.wav ITA_KANSAI_EMOTION_046.wav
move 別にブルマに特別な関心があるわけやない。.wav ITA_KANSAI_EMOTION_047.wav
move そないなフェティシズムはあらへんと思う。.wav ITA_KANSAI_EMOTION_048.wav
move ウッド夫人がこさえてくれるおいしい田舎風の料理を食べたし、ミルクをようさん飲みました。.wav ITA_KANSAI_EMOTION_049.wav
move うちのかみさんが瓶を割ってしもたもんで、勝手場の床が牛乳まみれになっとる。.wav ITA_KANSAI_EMOTION_050.wav
move 喧嘩しとった二人の子ぉは、お互いにしかめっ面をして座っとった。.wav ITA_KANSAI_EMOTION_051.wav
move 事業をやりもって、事業が世話んなっとる不動産を、切って売ってしたろなんて有り得へんねん。.wav ITA_KANSAI_EMOTION_052.wav
move せやけどペパーバーグは、そのオウムを研究することによって、動物に対する考え方が変わったと言うとる。.wav ITA_KANSAI_EMOTION_053.wav
move パックマンは何かしとったら、追ってくるモンスターを逆襲して食ぅたれるようになる。.wav ITA_KANSAI_EMOTION_054.wav
move その数百年後に、フォークが西洋のテーブルに現れることになるが、すぐに受け入れられたわけやなかった。.wav ITA_KANSAI_EMOTION_055.wav
move トップのリーダーは犬の行動学やったらアルファっちゅうて、後ベータ、ガンマって続くんや。.wav ITA_KANSAI_EMOTION_056.wav
move ウィーンまで歩いたらどんぐらいかかるやろか？.wav ITA_KANSAI_EMOTION_057.wav
move すんません、この辺はよおわからんのですわ。.wav ITA_KANSAI_EMOTION_058.wav
move 目標はな、授業をどんなんにするか決めるときの、学生がええ感じに勉強してくれるメディア教材の選び方と、使い方を解っとくっちゅうことや。.wav ITA_KANSAI_EMOTION_059.wav
move とりあえず店の前、掃除しといてくれへんか？打ち水も頼んます。.wav ITA_KANSAI_EMOTION_060.wav
move 人々はトーナメントが始まる何ヶ月も前に、これらの入場券を買うとる。.wav ITA_KANSAI_EMOTION_061.wav
move 彼女の魅力は言葉ではうまいこと言えへん、とその芸術家は叫んだ。.wav ITA_KANSAI_EMOTION_062.wav
move 見たらすぐわかる様なことをえらい小難しぃように言うてくる奴は、あんまり頭がええ様には思わん。.wav ITA_KANSAI_EMOTION_063.wav
move デザインも、アーチ型のロゴデザインにより、今風で登場感、躍動感あるもんに仕上げました。.wav ITA_KANSAI_EMOTION_064.wav
move そないに急いて運転して、一体どこへ行くっちゅうねん。.wav ITA_KANSAI_EMOTION_065.wav
move 時間はあるさかい、安全運転で頼むで。.wav ITA_KANSAI_EMOTION_066.wav
move ディスプレイはモニタとも言うて、コンピュータやらの機器から出力される静止画、それか動画の映像信号を表示する機器ってやつや。.wav ITA_KANSAI_EMOTION_067.wav
move 撃ち合いがちょっとマシんなったとき、おとんが走ってフラットへ行って、私らにサンドイッチ持ってきてくれたわ。.wav ITA_KANSAI_EMOTION_068.wav
move ギリシャのフットボールの試合やと、かたっぽのチームの選手は、相手チームの陣地のラインの向こう側へボールを持ってこうとしたんやわ。.wav ITA_KANSAI_EMOTION_069.wav
move 泳者のシンディー・ニコラスは、へとへとんなって泳ぎ切った後、ドーバーでよぉやっと陸へ上がってきよったけど、海峡水泳協会のスポークスマンは、彼女がめっちゃ元気やと発表した。.wav ITA_KANSAI_EMOTION_070.wav
move 若い男と女が人里離れた洋館で恐怖の一夜を過ごすっちゅう、ホラーの定番や。.wav ITA_KANSAI_EMOTION_071.wav
move 一つには、西洋人やないやつらが自分ら独自の文化に誇りを持ち始めてきたっちゅうことと、また一つは、フォーク使わへんとこはいっちゃん高い出生率の地域を抱えとるっちゅう理由から、これはまぁ合うとる。.wav ITA_KANSAI_EMOTION_072.wav
move 私らは恐ろしいとこで生きとって、苦しんどるんや。.wav ITA_KANSAI_EMOTION_073.wav
move 太陽も花も楽しめへんし、私らの子供時代も楽しめへんのよ。.wav ITA_KANSAI_EMOTION_074.wav
move 弊社のエンジニアが日本の中で売っとるよう似た奴と比べたらどないなっとるかと思って見たら、めっちゃええ感じでやってけそうな感じやった。.wav ITA_KANSAI_EMOTION_075.wav
move ノースウエスタン大学の研究者、アイリーン・ペパーバーグは、オウムは人の口まねをするだけやなく言葉の意味を学ぶことができるちゅうことを発見しぃつつある。.wav ITA_KANSAI_EMOTION_076.wav
move 名前をテョといいます。.wav ITA_KANSAI_EMOTION_077.wav
move ぴゅうぴゅう風が吹きこんでくる。.wav ITA_KANSAI_EMOTION_078.wav
move キェー。ギェー。イェーイ。.wav ITA_KANSAI_EMOTION_079.wav
move ひぇーん。びぇーん。ぴぇーん。.wav ITA_KANSAI_EMOTION_080.wav
move プリミェー。ミェルン。ニェン。.wav ITA_KANSAI_EMOTION_081.wav
move ステューデント。ダブルデュアル。.wav ITA_KANSAI_EMOTION_082.wav
move エテュード。エデュケーショナル。サブスティテューション。.wav ITA_KANSAI_EMOTION_083.wav
move ジャデャクシュ。.wav ITA_KANSAI_EMOTION_084.wav
move ブレンドデョート。.wav ITA_KANSAI_EMOTION_085.wav
move イデュスルファーゼ。.wav ITA_KANSAI_EMOTION_086.wav
move あっあの。.wav ITA_KANSAI_EMOTION_087.wav
move いっいえ。.wav ITA_KANSAI_EMOTION_088.wav
move えっえぇ。.wav ITA_KANSAI_EMOTION_089.wav
move おっおい。.wav ITA_KANSAI_EMOTION_090.wav
move んーとな。.wav ITA_KANSAI_EMOTION_091.wav
move アンツィオ。.wav ITA_KANSAI_EMOTION_092.wav
move エンツォ。.wav ITA_KANSAI_EMOTION_093.wav
move カートゥーン。.wav ITA_KANSAI_EMOTION_094.wav
move スィーディー。.wav ITA_KANSAI_EMOTION_095.wav
move ズィーブラ。.wav ITA_KANSAI_EMOTION_096.wav
move デピュティーガバナー。.wav ITA_KANSAI_EMOTION_097.wav
move エリュシオン。.wav ITA_KANSAI_EMOTION_098.wav
move ガリェント。.wav ITA_KANSAI_EMOTION_099.wav
move ラーテャン。.wav ITA_KANSAI_EMOTION_100.wav